### ISSUE TITLE
Toggl Retrospection 模板的新需求

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#118]
* [x] 关于工作项目的更精确计算：工作应算5天，而不是按7天计算 -> duplicated as https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/10 https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/14
* [x] 统计特定 Project 总体时间、每日时间（比如 foosball、赖床等） -> toggl built in functionality
* [x] 统计某个 Project 下特定项目（通过 description 来筛选）的总体时间、每日时间（比如 morning cleanup 等，一日中可能会出现，也可能不会出现，还有可能多次出现；又比如浪费 Project 下不同浪费项目的占比，等）https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/16
* [x] 为每个 project 增加一份 Description 模板，详细至 Description 内包含什么 tag，什么前缀，以区分出项目下的具体类型 #120
* [x] Summary 模板中增加工作日、周末的计数 https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/10
* [x] Summary 模板中，剔除掉没有计时的日子（total_grands = 0) https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/11
* [x] Client Summary 模板中，工作相关的条目都按实际工作日计算，需要排除掉周末 https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/14
* [x] 每个 summary 都增加一个计算过程可视化？比如参与计算的天数、排除掉的工作日等 https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/12
* [x] 假期的计算，是人为设置，还是自动计算？https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/12
* [x] 支持 toggl project - github repo 的一一对应，计算 velocity 等 https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/15

## Nice to have, 因为看起来很难

* [x] 现在已能给出 url，能否给出自动截图的功能？ https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/17
* [x] Actions from last retro，能否自动 copy 过来？ https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/18
* [x] 产出如 Toggl 一样的饼状图或报告图？-> https://github.com/linesh-simplicity/toggl-retro-template-data-generator/issues/17 中有讨论，要看做这个事情的目标或者意义是什么
