### ISSUE TITLE
Epic - 博客回炉重造 2018

### ISSUE THREAD

**Issue by linesh-simplicity** [linesh-simplicity/linesh-simplicity.github.io#203]
修复一下博客首页不能展示超过2017年文章的 bug。。。

最近觉得撸代码没劲儿，一方面项目上逐渐学到一些架构性的东西。以往醉心于技术架构和整洁代码，但现在如果再让我从头起个（产品型的）项目，我一定会从头就把这两个事情搞好：埋点统计和用户体验。UX 这块是需要加强的。

最近发表 React 单元测试的文章，得到很多大神的反馈。点进去，看到一篇文章讲项目与产品的区别，甚是契合最近的心态。项目关注成败，产品关注价值，这是本质不同。当你在做项目时，埋点和 UX 是你不关心的两个部分。当然，我所说的关心是愿意投入资源的关心，是不投入产品就可能死掉的关心。它是生死项，不是可选项。讲到生死项，不禁想到优秀方法论的伟大能力。讲到伟大能力，不禁想到伟大责任。讲到责任，想到英雄；讲到英雄，想到不得好死。

说到关注价值，不禁又想到价值，想到虚空。做一个软件产品可以给用户带来价值，但用户是什么？用户为什么需要这个价值？用户有什么需求？人有什么需求？人又是什么？什么是有价值的事情？什么是有意义的事情？接受过良好的教育，又有先进的方法论护身，最终就是为了写代码、做管理、做经理吗？但是别人真的需要你来创造什么「价值」呢？看起来我好像热爱技术，但是我热爱的是什么呢？为了那个尚未找到的意义，我为什么会坐在这里，写着这一行代码呢？搞不懂。

噢对了，虽说提到「价值」，但还是不要因为敏捷，就觉得所有场景下都是越快上线验收价值越高。可能有的产品频繁上线也不一定就能越快获得价值呢（比如最近了解到，以线上作为补充，主要以线下渠道为主的应用），可能还是跟产品形态有关系的。我不是说它一定是错的，而是说在真正实践之前要克制自己不要有这个先入为主的预设。怎么实践呢，多了解了解商业了只能。

不管如何，还是尽量乐观探索。

## 正题

粗粗想了一下，想要做产品的感觉，可以从自己的博客入手。一方面我很想发出自己的声音，一方面又觉得此种声音没有意义。无所谓强弱好坏。无所谓产品价值。无所谓意义。如果要说博客的价值的话，我觉得是，在表达中表达着。如此而已。

一拍脑袋，有这么些事情想做做：

* [x] 埋点统计 #204 
  * 多渠道埋点 - rss，网页，手机设备，推荐链接的来源占比等
  * 其他基本埋点，页面埋点和事件埋点
* [x] 架构设计 - 希望能支持多种语言，未来找不到人生意义了，就找种新的编程语言来实现一遍博客。或许要弃用 Jekyll #205 
* [x] 性能 #206 
* [x] ui设计 - 酷炫一点咯。支持可切换的markdown主题，所以注意ux管理 #207 
* [x] 使用最新的技术栈 navigation啊 dva啊 firebase啊 vue啊 #208 
* [x] 基础设施搭建 - CI、测试工具、自动部署等 #209
* [x] 支持单篇文章的阅读，有目录，简介，沉浸式阅读 #210
* [x] 单篇文章可以评论 #211
* [x] 单篇文章可以点赞、点差评 #212
* [x] 首页列表 #213 
* [x] 首页有目录，可按目录分类文章。主要有翻译目录 #214 
* [x] 首页有专题。专题支持可扩展，可新增一个专题，比如翻译某个文章的专题，udacity专题等 #215 
* [x] 草稿区。没写完的文章也可以看到、给反馈 #216
* [x] 他说。他总是有些话要说的 #217
* [x] 数据展示，如alfred数据，等以简明图表示即可 #218
* [x] 清理 Github issues，永远不会再用的 close 掉，还可以输出成文章的 reopen，待处理的 open 着 #219

**Comment by JimmyLv** [comment]
太好了，资持！

**Comment by linesh-simplicity** [comment]
博客换地方了。这个博客 issue 以后只用来发想法。
